name: doc

on:
  push:
    branch: [ "master" ]

env: 
  CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
  CI_COMMIT_AUTHOR: Continuous Integration

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: Generate docs
      run: rustdoc src/lib.rs
    - name: Push
      run: |
        git add .
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "username@users.noreply.github.com"
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push origin -u doc
    