name: doc

on:
  push:
    branch: [ "master" ]

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: Generate docs
      run: rustdoc src/lib.rs
    - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: doc
        FOLDER: doc
        GITHUB_TOKEN: ${{ secrets.PAT }}
        MESSAGE: "Doc push: ({sha}) {msg}"
    