name: doc

on:
  push:
    branch: [ "master" ]

env: 
  CI_COMMIT_MESSAGE: Rust-doc bot generates documentation automatically
  CI_COMMIT_AUTHOR: Rust-doc bot

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: Generate docs
      run: rustdoc src/lib.rs
    - name: Clean
      run: |
        shopt -s extglob
        rm -rf -v !("doc") ..?* .[!.]*
        mv doc/* .
        rm -rf doc
    - name: Push
      run: |
        git add .
        git checkout -b doc
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "username@users.noreply.github.com"
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push --set-upstream origin doc
    